<?php

namespace App\Controller\Api\Inventory;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

class InventoryController extends AbstractController
{

}
/**
 * TODO: ALL BELOW
 */
//! GET INVENTORIE FROM ONE ROOM OR ALL-ROOMS FROM A MONTH
//! POST INVENTORIE ALL-ROOMS FROM A MONTH ADDING EACH ROOM INVENTORIE TO THE ALL-ROOMS EXCEL FILE..
//! ..AND BE ABLE TO ADD A NEW ROW OR COLUMN TO THE EXCEL FILE AND ADD THE CORRESPONDING DATE
//! POST INVENTORIE FROM ONE ROOM FROM A MONTH STARTING WITH AN EMPTY EXCEL FILE
//! UPDATE INVENTORIE FROM ONE ROOM OR ALL-ROOMS FROM A MONTH 
//! UPDATE INVENTORIE ALL-ROOMS 
//! UPLOAD TO API KIT for pdf image or to server file storage THE NEW FILE INVENTORY FROM ONE ROOM OR ALL-ROOMS FROM A MONTH and update excelfile path
//! DELETE INVENTORIE FROM ONE ROOM OR ALL-ROOMS FROM A MONTH
//! Look for inventories by the room name and for a period ou pagination

//* METHOD SEND EMAIL WITH INVENTORIE FILE ATTACHED
//* METHOD GET EMPTY ORIGINAL EXCEL FILE FROM ONE ROOM OR ALL-ROOMS AND ADD THE CORRESPONDING DATE
//* METHOD ADD ROOM TO ALL-ROOMS EXCEL FILE NEW OR EXISTING
//* METHOD CRUD FOR MANAGING ROW AND COLUMN ON EXCEL FILE INSIDE SPREADSHEET SERVICE, 
//* CAREFUL THAT IF COLUMN MUST BE CHANGED THEY MUST BE FOR ALL EXCEL ROOMS ORIGINAL FILE,
//* ...SO WE MUST HAVE A BASE COLUMN EXCEL FILE FOR ALL ROOMS 
//* ....WHEN GETTING A NEW ORIGINAL FILE WE MUST BUILT IT WITH BASE COLUMN 
//* .....AND THEN FEED WITH EXISTING ROW; LETTING EMPTY VALUE ROW ON NEW COLUMN

